### ISSUE TITLE
config

### ISSUE THREAD

**Issue by nicotravassos** [anandre/dragon-rpg#2]
Hi @anandre,

Kindly include sample config.sample.json within repository.

**Comment by anandre** [comment]
Yeah, I'll get around to it, I haven't been able to keep up on as much as I'd like.  It's a pretty simple JSON, `token` is the Discord token and `pgfoo` is all of the needed info to connect to the PostgreSQL database.

```js
{
    "token": "",
    "pgadd": "",
    "pgpass": "",
    "pguser": "",
    "pgserv": "",
    "pgport": "",
    "pgdb": ""
}```

**Comment by nicotravassos** [comment]
Thanks @anandre
